repos:
  # black
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: git://github.com/guykisel/prospector-mirror
    rev: '7ff847e779347033ebbd9e3b88279e7f3a998b45'
    hooks:
      - id: prospector