version: 2.1

orbs:
  python: circleci/python@0.3.0
  codecov: codecov/codecov@1.1.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/install-deps:
          dependency-file: requirements-dev.txt
      - python/save-cache
      - run:
          name: test
          command: python setup.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - codecov/upload
  deploy:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/install-deps:
          dependency-file: requirements-dev.txt
      - python/save-cache
      - run:
          name: verify git tag vs. version
          command: python setup.py verify
      - python/dist
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: twine upload dist/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only: release