version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test-3_8:
    executor: python/default
    working_directory: ~/clouddiscovery
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: pip install --user -r requirements-dev.txt
          name: Install Dev Dependencies
      - python/save-cache
      - run:
          command: py.test
          name: Test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test-3_8
