version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/install-deps:
          dependency-file: requirements-dev.txt
      - python/save-cache
      - python/test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test
